apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
  namespace: chatbot
  labels:
    app: chatbot-api
data:
  MODEL: "gpt-4o-mini"
  MODE: "local"                                        # cloud | local — surchargé par deploy-k8s-local
  LOCAL_BASE_URL: "http://host.docker.internal:1234/v1" # surchargé par deploy-k8s-local
  LOCAL_MODEL: "mistral-7b-instruct"                   # surchargé par deploy-k8s-local
  DB_PATH: "/app/data/chat.db"
  CHROMA_PATH: "/app/data/chroma_db"
  RAG_COLLECTION: "chatbot_docs"
  RAG_TOP_K: "3"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  ALLOWED_ORIGINS: "http://localhost:8080,http://localhost:3000"
